sed 's/3d_photo.png/3d_photo.jpg/g' <data.py>temp
mv temp data.py
sed 's/accomodation.png/accomodation.jpg/g' <data.py>temp
mv temp data.py
sed 's/adverse_mining.png/adverse_mining.jpg/g' <data.py>temp
mv temp data.py
sed 's/Android.png/Android.jpg/g' <data.py>temp
mv temp data.py
sed 's/aoe2.png/aoe2.jpg/g' <data.py>temp
mv temp data.py
sed 's/aoe3.png/aoe3.jpg/g' <data.py>temp
mv temp data.py
sed 's/Architect2.png/Architect2.jpg/g' <data.py>temp
mv temp data.py
sed 's/astro.png/astro.jpg/g' <data.py>temp
mv temp data.py
sed 's/astro_talk.png/astro_talk.jpg/g' <data.py>temp
mv temp data.py
sed 's/AUGMENTED.png/AUGMENTED.jpg/g' <data.py>temp
mv temp data.py
sed 's/AUTOMATA_NEW.png/AUTOMATA_NEW.jpg/g' <data.py>temp
mv temp data.py
sed 's/Best Ceo.png/Best Ceo.jpg/g' <data.py>temp
mv temp data.py
sed 's/Beyond_Earth.png/Beyond_Earth.jpg/g' <data.py>temp
mv temp data.py
sed 's/BIZ.png/BIZ.jpg/g' <data.py>temp
mv temp data.py
sed 's/blast_mine_ventilation.png/blast_mine_ventilation.jpg/g' <data.py>temp
mv temp data.py
sed 's/blitzkrieg.png/blitzkrieg.jpg/g' <data.py>temp
mv temp data.py
sed 's/BluePrint.png/BluePrint.jpg/g' <data.py>temp
mv temp data.py
sed 's/Bridge_design.png/Bridge_design.jpg/g' <data.py>temp
mv temp data.py
sed 's/campussocialinnovation.png/campussocialinnovation.jpg/g' <data.py>temp
mv temp data.py
sed 's/casestudychallenge.png/casestudychallenge.jpg/g' <data.py>temp
mv temp data.py
sed 's/Chemical_Breakdown.png/Chemical_Breakdown.jpg/g' <data.py>temp
mv temp data.py
sed 's/chemmain.png/chemmain.jpg/g' <data.py>temp
mv temp data.py
sed 's/civilmain.png/civilmain.jpg/g' <data.py>temp
mv temp data.py
sed 's/CODE_KOMBAT.png/CODE_KOMBAT.jpg/g' <data.py>temp
mv temp data.py
sed 's/Colossus.png/Colossus.jpg/g' <data.py>temp
mv temp data.py
sed 's/Comps_Main.png/Comps_Main.jpg/g' <data.py>temp
mv temp data.py
sed 's/contacts.png/contacts.jpg/g' <data.py>temp
mv temp data.py
sed 's/COUNTERSTRIKE.png/COUNTERSTRIKE.jpg/g' <data.py>temp
mv temp data.py
sed 's/Dance.png/Dance.jpg/g' <data.py>temp
mv temp data.py
sed 's/data_analysischallenge.png/data_analysischallenge.jpg/g' <data.py>temp
mv temp data.py
sed 's/dOTA.png/dOTA.jpg/g' <data.py>temp
mv temp data.py
sed 's/ECTF.png/ECTF.jpg/g' <data.py>temp
mv temp data.py
sed 's/Equipment Demo.png/Equipment Demo.jpg/g' <data.py>temp
mv temp data.py
sed 's/events.png/events.jpg/g' <data.py>temp
mv temp data.py
sed 's/EXHIBITION.png/EXHIBITION.jpg/g' <data.py>temp
mv temp data.py
sed 's/fantasticity2.png/fantasticity2.jpg/g' <data.py>temp
mv temp data.py
sed 's/fifa.png/fifa.jpg/g' <data.py>temp
mv temp data.py
sed 's/Finance.png/Finance.jpg/g' <data.py>temp
mv temp data.py
sed 's/foxxhunt.png/foxxhunt.jpg/g' <data.py>temp
mv temp data.py
sed 's/gaming.png/gaming.jpg/g' <data.py>temp
mv temp data.py
sed 's/GeneralEvents.png/GeneralEvents.jpg/g' <data.py>temp
mv temp data.py
sed 's/Green_Innovation_Challenge.png/Green_Innovation_Challenge.jpg/g' <data.py>temp
mv temp data.py
sed 's/Green Product Design.png/Green Product Design.jpg/g' <data.py>temp
mv temp data.py
sed 's/Green_Product_Design.png/Green_Product_Design.jpg/g' <data.py>temp
mv temp data.py
sed 's/HACKING.png/HACKING.jpg/g' <data.py>temp
mv temp data.py
sed 's/HANGMAN_MAIN.png/HANGMAN_MAIN.jpg/g' <data.py>temp
mv temp data.py
sed 's/HR.png/HR.jpg/g' <data.py>temp
mv temp data.py
sed 's/IDP.png/IDP.jpg/g' <data.py>temp
mv temp data.py
sed 's/INSCRIPTION.png/INSCRIPTION.jpg/g' <data.py>temp
mv temp data.py
sed 's/lastword.png/lastword.jpg/g' <data.py>temp
mv temp data.py
sed 's/Launchpad.png/Launchpad.jpg/g' <data.py>temp
mv temp data.py
sed 's/marathon_final.png/marathon_final.jpg/g' <data.py>temp
mv temp data.py
sed 's/MARKENZA.png/MARKENZA.jpg/g' <data.py>temp
mv temp data.py
sed 's/MBA.png/MBA.jpg/g' <data.py>temp
mv temp data.py
sed 's/mech.png/mech.jpg/g' <data.py>temp
mv temp data.py
sed 's/megapixel.png/megapixel.jpg/g' <data.py>temp
mv temp data.py
sed 's/meta_magic.png/meta_magic.jpg/g' <data.py>temp
mv temp data.py
sed 's/MetaMagic.png/MetaMagic.jpg/g' <data.py>temp
mv temp data.py
sed 's/Metamain.png/Metamain.jpg/g' <data.py>temp
mv temp data.py
sed 's/mindbend.png/mindbend.jpg/g' <data.py>temp
mv temp data.py
sed 's/Mine_Quest.png/Mine_Quest.jpg/g' <data.py>temp
mv temp data.py
sed 's/Mine_Rush.png/Mine_Rush.jpg/g' <data.py>temp
mv temp data.py
sed 's/mining_innovation.png/mining_innovation.jpg/g' <data.py>temp
mv temp data.py
sed 's/mining.png/mining.jpg/g' <data.py>temp
mv temp data.py
sed 's/mockstock.png/mockstock.jpg/g' <data.py>temp
mv temp data.py
sed 's/nfs.png/nfs.jpg/g' <data.py>temp
mv temp data.py
sed 's/Nirvana.png/Nirvana.jpg/g' <data.py>temp
mv temp data.py
sed 's/NIT-K-event.png/NIT-K-event.jpg/g' <data.py>temp
mv temp data.py
sed 's/PerfectMachine.png/PerfectMachine.jpg/g' <data.py>temp
mv temp data.py
sed 's/Pinball.png/Pinball.jpg/g' <data.py>temp
mv temp data.py
sed 's/PRODUCT_DESIGN_123.png/PRODUCT_DESIGN_123.jpg/g' <data.py>temp
mv temp data.py
sed 's/Proteus.png/Proteus.jpg/g' <data.py>temp
mv temp data.py
sed 's/PsychRoom.png/PsychRoom.jpg/g' <data.py>temp
mv temp data.py
sed 's/RC Aircraft.png/RC Aircraft.jpg/g' <data.py>temp
mv temp data.py
sed 's/RC_Aircraft.png/RC_Aircraft.jpg/g' <data.py>temp
mv temp data.py
sed 's/RECTIFY.png/RECTIFY.jpg/g' <data.py>temp
mv temp data.py
sed 's/ROBOTICS.png/ROBOTICS.jpg/g' <data.py>temp
mv temp data.py
sed 's/RoboWars.png/RoboWars.jpg/g' <data.py>temp
mv temp data.py
sed 's/saprsh.png/saprsh.jpg/g' <data.py>temp
mv temp data.py
sed 's/Satellite Simulator.png/Satellite Simulator.jpg/g' <data.py>temp
mv temp data.py
sed 's/Sce.png/Sce.jpg/g' <data.py>temp
mv temp data.py
sed 's/SEMphotography.png/SEMphotography.jpg/g' <data.py>temp
mv temp data.py
sed 's/SEMTEMExpo.png/SEMTEMExpo.jpg/g' <data.py>temp
mv temp data.py
sed 's/SIMPLICITY.png/SIMPLICITY.jpg/g' <data.py>temp
mv temp data.py
sed 's/SIMPLINEER.png/SIMPLINEER.jpg/g' <data.py>temp
mv temp data.py
sed 's/sky_lantern.png/sky_lantern.jpg/g' <data.py>temp
mv temp data.py
sed 's/Software Demo.png/Software Demo.jpg/g' <data.py>temp
mv temp data.py
sed 's/sponsors.png/sponsors.jpg/g' <data.py>temp
mv temp data.py
sed 's/starwars.png/starwars.jpg/g' <data.py>temp
mv temp data.py
sed 's/Symphony.png/Symphony.jpg/g' <data.py>temp
mv temp data.py
sed 's/technites.png/technites.jpg/g' <data.py>temp
mv temp data.py
sed 's/techspeak2.png/techspeak2.jpg/g' <data.py>temp
mv temp data.py
sed 's/techspeak3.png/techspeak3.jpg/g' <data.py>temp
mv temp data.py
sed 's/techspeak.png/techspeak.jpg/g' <data.py>temp
mv temp data.py
sed 's/Techspeak.png/Techspeak.jpg/g' <data.py>temp
mv temp data.py
sed 's/the_portal.png/the_portal.jpg/g' <data.py>temp
mv temp data.py
sed 's/trade_off.png/trade_off.jpg/g' <data.py>temp
mv temp data.py
sed 's/trailblazer.png/trailblazer.jpg/g' <data.py>temp
mv temp data.py
sed 's/tronix3.png/tronix3.jpg/g' <data.py>temp
mv temp data.py
sed 's/tronix.png/tronix.jpg/g' <data.py>temp
mv temp data.py
sed 's/Velocity.png/Velocity.jpg/g' <data.py>temp
mv temp data.py
sed 's/viewer1.png/viewer1.jpg/g' <data.py>temp
mv temp data.py
sed 's/viewer2.png/viewer2.jpg/g' <data.py>temp
mv temp data.py
sed 's/viewer3.png/viewer3.jpg/g' <data.py>temp
mv temp data.py
sed 's/viewer.png/viewer.jpg/g' <data.py>temp
mv temp data.py
sed 's/VIRTUAL_BOUNTY2.png/VIRTUAL_BOUNTY2.jpg/g' <data.py>temp
mv temp data.py
sed 's/Waltz.png/Waltz.jpg/g' <data.py>temp
mv temp data.py
sed 's/workshop2.png/workshop2.jpg/g' <data.py>temp
mv temp data.py
sed 's/workshop.png/workshop.jpg/g' <data.py>temp
mv temp data.py
sed 's/WrightFlight.png/WrightFlight.jpg/g' <data.py>temp
mv temp data.py
